<?php

require_once __DIR__.'/../autoload.php';

use Vnay92\Fluent\Monolog\FluentHandler;

// Start fluentd on the local host using the sample configuration file
// that can be generated by calling fluentd with the -s option.

$log = new Monolog\Logger('debug.monolog');

$log->pushHandler(new FluentHandler());

// add records to the log
$log->warning('Foo');
$log->error('Bar');
